env:
  es2021: true
  node: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent: ['warn', 2]
  object-curly-spacing: ['warn', 'always']
  require-jsdoc: 0
  valid-jsdoc: ['error', {
    requireReturn: false,
    requireReturnType: false,
    requireParamType: false,
  }]
  no-unused-vars: 0 # some problem while use enum
